
<!-- CREATE SEQUENCE SEQ_CLIENTS START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;-->
<!--CREATE SEQUENCE SEQ_PROVIDERS START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;-->
<!--CREATE SEQUENCE SEQ_PRODUCTS START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;-->
<!--CREATE SEQUENCE SEQ_STATIONERIES START WITH 1 INCREMENT BY 1 MAXVALUE 99999 MINVALUE 1;-->

<-- CLIENTES -->

INSERT INTO CLIENTS (ID_CLIENT, UPDATE_DATE, UPDATE_USER, DNI_CLIENT, NAME_CLIENT, SURNAME_CLIENT) VALUES (SEQ_CLIENTS.NEXTVAL, null, null, '11111111A', 'Pablo', 'Picasso');
INSERT INTO CLIENTS (ID_CLIENT, UPDATE_DATE, UPDATE_USER, DNI_CLIENT, NAME_CLIENT, SURNAME_CLIENT) VALUES (SEQ_CLIENTS.NEXTVAL, null, null, '22222222B', 'Diego', 'Velázquez');
INSERT INTO CLIENTS (ID_CLIENT, UPDATE_DATE, UPDATE_USER, DNI_CLIENT, NAME_CLIENT, SURNAME_CLIENT) VALUES (SEQ_CLIENTS.NEXTVAL, null, null, '33333333C', 'Joaquín', 'Sorolla');
INSERT INTO CLIENTS (ID_CLIENT, UPDATE_DATE, UPDATE_USER, DNI_CLIENT, NAME_CLIENT, SURNAME_CLIENT) VALUES (SEQ_CLIENTS.NEXTVAL, null, null, '44444444D', 'Salvador', 'Dalí');
INSERT INTO CLIENTS (ID_CLIENT, UPDATE_DATE, UPDATE_USER, DNI_CLIENT, NAME_CLIENT, SURNAME_CLIENT) VALUES (SEQ_CLIENTS.NEXTVAL, null, null, '55555555E', 'Valeriano', 'Bécquer');


<-- PROVEEDORES -->

INSERT INTO PROVIDERS (ID_PROVIDER, UPDATE_DATE, UPDATE_USER, CIF_PROVIDER, CITY_PROVIDER, NAME_PROVIDER, PROVINCE_PROVIDER) VALUES (SEQ_PROVIDERS.NEXTVAL, null, null, '66666666F', 'Sevilla', 'SuperProveedor', 'Sevilla');
INSERT INTO PROVIDERS (ID_PROVIDER, UPDATE_DATE, UPDATE_USER, CIF_PROVIDER, CITY_PROVIDER, NAME_PROVIDER, PROVINCE_PROVIDER) VALUES (SEQ_PROVIDERS.NEXTVAL, null, null, '77777777G', 'Segovia', 'MegaProveedor', 'Segovia');
INSERT INTO PROVIDERS (ID_PROVIDER, UPDATE_DATE, UPDATE_USER, CIF_PROVIDER, CITY_PROVIDER, NAME_PROVIDER, PROVINCE_PROVIDER) VALUES (SEQ_PROVIDERS.NEXTVAL, null, null, '88888888H', 'Madrid', 'GigaProveedor', 'Madrid');
INSERT INTO PROVIDERS (ID_PROVIDER, UPDATE_DATE, UPDATE_USER, CIF_PROVIDER, CITY_PROVIDER, NAME_PROVIDER, PROVINCE_PROVIDER) VALUES (SEQ_PROVIDERS.NEXTVAL, null, null, '99999999I', 'Toledo', 'TeraProveedor', 'Toledo');
INSERT INTO PROVIDERS (ID_PROVIDER, UPDATE_DATE, UPDATE_USER, CIF_PROVIDER, CITY_PROVIDER, NAME_PROVIDER, PROVINCE_PROVIDER) VALUES (SEQ_PROVIDERS.NEXTVAL, null, null, '10101010J', 'El Escorial', 'PetaProveedor', 'Madrid');


<-- PAPELERÍAS -->

INSERT INTO STATIONERIES (ID_STATIONERY, UPDATE_DATE, UPDATE_USER, CIF_STATIONERY, CITY_STATIONERY, NAME_STATIONERY, PROVINCE_STATIONERY) VALUES (SEQ_STATIONERIES.NEXTVAL, null, null, '12121212K', 'Sevilla', 'Tijeras SL', 'Sevilla');
INSERT INTO STATIONERIES (ID_STATIONERY, UPDATE_DATE, UPDATE_USER, CIF_STATIONERY, CITY_STATIONERY, NAME_STATIONERY, PROVINCE_STATIONERY) VALUES (SEQ_STATIONERIES.NEXTVAL, null, null, '13131313L', 'Segovia', 'Cartulinas City', 'Segovia');
INSERT INTO STATIONERIES (ID_STATIONERY, UPDATE_DATE, UPDATE_USER, CIF_STATIONERY, CITY_STATIONERY, NAME_STATIONERY, PROVINCE_STATIONERY) VALUES (SEQ_STATIONERIES.NEXTVAL, null, null, '14141414M', 'Madrid', 'Pegamento Imedio', 'Madrid');
INSERT INTO STATIONERIES (ID_STATIONERY, UPDATE_DATE, UPDATE_USER, CIF_STATIONERY, CITY_STATIONERY, NAME_STATIONERY, PROVINCE_STATIONERY) VALUES (SEQ_STATIONERIES.NEXTVAL, null, null, '15151515N', 'Toledo', 'El país de los rotuladores', 'Toledo');
INSERT INTO STATIONERIES (ID_STATIONERY, UPDATE_DATE, UPDATE_USER, CIF_STATIONERY, CITY_STATIONERY, NAME_STATIONERY, PROVINCE_STATIONERY) VALUES (SEQ_STATIONERIES.NEXTVAL, null, null, '16161616O', 'El Escorial', 'Carpetas Guardatodo', 'Madrid');


<-- PRODUCTOS -->

INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Cuaderno grande', 2.8, 1, 1);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Cuaderno pequeño', 2.3, 2, 1);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Cuaderno de rayas', 2.5, 5, 1);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Tijeras', 1.5, 2, 2);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Tijeras de electricista', 5.5, 3, 2);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Tijeras de costura', 3.5, 5, 2);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Fotocopias color', 0.10, 1, 3);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Fotocopias B/N', 0.03, 2, 3);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Fotocopias A3', 0.05, 4, 3);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Pegamento de barra', 1.5, 3, 4);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Pegamento de cola', 1.75, 4, 4);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Pegamento imedio', 2.75, 5, 4);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Cartulina grande', 0.5, 2, 5);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Cartulina pequeña', 0.1, 4, 5);
INSERT INTO PRODUCTS (ID_PRODUCT, UPDATE_DATE, UPDATE_USER, NAME_PRODUCT, PRICE_PRODUCT, ID_CLIENT, ID_PROVIDER) VALUES (SEQ_PRODUCTS.NEXTVAL, null, null, 'Cartulina purpurina', 0.75, 5, 5);


<-- CLIENTES-PAPELERÍAS -->

INSERT INTO STATIONERIES_CLIENTS (ID_STATIONERY, ID_CLIENT) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '12121212K'), (SELECT ID_CLIENT FROM CLIENTS WHERE DNI_CLIENT = '11111111A')); 
INSERT INTO STATIONERIES_CLIENTS (ID_STATIONERY, ID_CLIENT) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '12121212K'), (SELECT ID_CLIENT FROM CLIENTS WHERE DNI_CLIENT = '33333333C')); 
INSERT INTO STATIONERIES_CLIENTS (ID_STATIONERY, ID_CLIENT) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '13131313L'), (SELECT ID_CLIENT FROM CLIENTS WHERE DNI_CLIENT = '44444444D')); 
INSERT INTO STATIONERIES_CLIENTS (ID_STATIONERY, ID_CLIENT) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '15151515N'), (SELECT ID_CLIENT FROM CLIENTS WHERE DNI_CLIENT = '22222222B')); 
INSERT INTO STATIONERIES_CLIENTS (ID_STATIONERY, ID_CLIENT) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '16161616O'), (SELECT ID_CLIENT FROM CLIENTS WHERE DNI_CLIENT = '33333333C')); 
INSERT INTO STATIONERIES_CLIENTS (ID_STATIONERY, ID_CLIENT) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '14141414M'), (SELECT ID_CLIENT FROM CLIENTS WHERE DNI_CLIENT = '55555555E')); 


<-- PROVEEDORES-PAPELERÍAS -->

INSERT INTO STATIONERIES_PROVIDERS (ID_STATIONERY, ID_PROVIDER) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '12121212K'), (SELECT ID_PROVIDER FROM PROVIDERS WHERE CIF_PROVIDER = '66666666F')); 
INSERT INTO STATIONERIES_PROVIDERS (ID_STATIONERY, ID_PROVIDER) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '12121212K'), (SELECT ID_PROVIDER FROM PROVIDERS WHERE CIF_PROVIDER = '88888888H')); 
INSERT INTO STATIONERIES_PROVIDERS (ID_STATIONERY, ID_PROVIDER) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '13131313L'), (SELECT ID_PROVIDER FROM PROVIDERS WHERE CIF_PROVIDER = '99999999I')); 
INSERT INTO STATIONERIES_PROVIDERS (ID_STATIONERY, ID_PROVIDER) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '15151515N'), (SELECT ID_PROVIDER FROM PROVIDERS WHERE CIF_PROVIDER = '77777777G')); 
INSERT INTO STATIONERIES_PROVIDERS (ID_STATIONERY, ID_PROVIDER) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '16161616O'), (SELECT ID_PROVIDER FROM PROVIDERS WHERE CIF_PROVIDER = '88888888H')); 
INSERT INTO STATIONERIES_PROVIDERS (ID_STATIONERY, ID_PROVIDER) VALUES ((SELECT ID_STATIONERY FROM STATIONERIES WHERE CIF_STATIONERY = '14141414M'), (SELECT ID_PROVIDER FROM PROVIDERS WHERE CIF_PROVIDER = '10101010J')); 
